// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package cn.yase.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.yase.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .cn.yase.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<cn.yase.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .cn.yase.proto.StudentResponse studentResponse = 1;</code>
   */
  cn.yase.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .cn.yase.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .cn.yase.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends cn.yase.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .cn.yase.proto.StudentResponse studentResponse = 1;</code>
   */
  cn.yase.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
